### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [rrjudd/jvsip#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by rrjudd** [comment]
For JVSIP all the "licensing" information is included in the Copyright file in the top level directory.  I suppose I can add a file called LICENSE.txt that says read Copyright file but I am not sure it is really needed.  My intentions seem clear from the documentation in the Copyright file and in a lot of the code.  My current intent is the MIT license.
